### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by kkaelin** [grandivory/ffxi-gearswap#1]
Hi there!  First of all, I'd like to say I love your project!  It's amazing and it's completely transformed the way I play FFXI.  I love the simplicity of being able to just set up gear sets for each of my jobs.  I do have a couple requests, and things I've found that might be useful to change when you get a chance.

1. I noticed that gearswap uses my generic midcast set for Refresh II, but my Refresh set for Refresh.  Would be nice to not have to define the set for each level of refresh.  I use "sets.midcast.Refresh" and sets.midcast["Refresh II] currently to circumvent the issue.

2. Being able to define sets for self enhancing spells and enhancing spells cast on others would be great.  As rdm I will use 2 different gear sets for this.

3.  Knowing a list of which spells are considered "skill" spells and which are not would also be useful.  For example, I use duration sets, skill/potency sets, and magic accuracy sets depending on what I am casting.  I would like to make sure I am using the correct sets for the correct spells.  Maybe add this to a readme file?  It might also be good to compile a list of example set definitions and such for the new user or the not well versed in lua user.

4.  Having a trigger for magic burst sets would also be super useful.

Thanks and keep up the great work!

**Comment by grandivory** [comment]
1. I fixed partial spell name matches so that they will happen before skill type matches. Now, `sets.midcast.Refresh` should match to either `Refresh` or `Refresh II`
2. Now, any spell-specific set can have "Self" appended to the end of its name to be used when casting on yourself. This is also true for cures and enhancing magic, e.g. `sets.midcast.EnhancingSelf` or `sets.midcast.EnhancingDurationSelf`
3. Skill spells can be found by looking in `ability-data.lua`. All of the spells that use skill sets instead of duration sets are listed under `EnhancingSpells`
4. I've added a new command, `gs c MB` to turn magic burst mode on. This will stay on for exactly one spell, no matter what you cast. If a `sets.midcast[spell name MB]` (like `sets.midcast.HelixMB`) or a more generic `sets.midcast.ElementalMB` is defined, that set will be used over the normal set.
